require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '16.0'
use_frameworks! :linkage => :static

target 'IOSMirror' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  pod 'google-cast-sdk-no-bluetooth', '~> 4.8'
end

# BroadcastExtension is self-contained; VideoToolbox & Network are system frameworks
target 'BroadcastExtension' do
  inherit! :none
end

post_install do |installer|
  react_native_post_install(
    installer,
    '../node_modules/react-native',
    :mac_catalyst_enabled => false
  )
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
      config.build_settings['ENABLE_BITCODE']             = 'NO'
      config.build_settings['CODE_SIGN_IDENTITY']         = ''
      config.build_settings['CODE_SIGNING_REQUIRED']      = 'NO'
      config.build_settings['CODE_SIGNING_ALLOWED']       = 'NO'
    end
  end
end
